### ISSUE TITLE
当把groupfi的nft划走后，my groups页面该群组变成了unknow了，见截图

### ISSUE THREAD

**Issue by tanglepay-dev** [TanglePay/GroupFi-trollbox#165]
![Image](https://github.com/TanglePay/GroupFi-trollbox/assets/42662926/ddc14ab6-e5a8-4305-9538-0d95a3efc829)

**Comment by zkk333** [comment]
还是unknow啊

**Comment by tanglepay-dev** [comment]
hide the group if no longer eligible

**Comment by zkk333** [comment]
@time-endless   这个页面还是显示着unknow

![Image](https://github.com/TanglePay/GroupFi-trollbox/assets/42662926/2f831eeb-1b47-4540-8b92-0b64626c75e4)

**Comment by zkk333** [comment]
还是存在unknown
![Image](https://github.com/TanglePay/GroupFi-trollbox/assets/42662926/1e3e7e01-4a8e-4d92-9fd7-8c646ff93053)

**Comment by zkk333** [comment]
测试通过，根据实际测试结果  比如a和b用户，a可以看到b加入的所有public群，看不到private群
