### ISSUE TITLE
目前来看  一分钟内一个用户发送多条消息，存在丢消息的问题,见截图

### ISSUE THREAD

**Issue by tanglepay-dev** [TanglePay/GroupFi-trollbox#194]
![Image](https://github.com/TanglePay/GroupFi-trollbox/assets/42662926/ed50c5af-6fe6-4957-9031-5b346f0329c9)

![Image](https://github.com/TanglePay/GroupFi-trollbox/assets/42662926/b92c8f40-93f6-4a4e-8e38-80c343228b0c)

**Comment by tanglepay-dev** [comment]
proposal for fix: get latest status from hornet/output/metadata to check if isSpent is true, false or spending.
@iotadex has more details.

**Comment by zkk333** [comment]
暂时看着没问题，连续发n条消息，消息都被另一个用户接收了

**Comment by zkk333** [comment]
有点改善，但是不多

**Comment by zkk333** [comment]
丢消息还是存在的

**Comment by zkk333** [comment]
测试通过，目前来看  基本不丢
