### ISSUE TITLE
Fix message rendering after cache clean up

### ISSUE THREAD

**Issue by tanglepay-dev** [TanglePay/GroupFi-trollbox#212]

**Comment by time-endless** [comment]
上周gw分享最后留的那个小尾巴：
用户缓存清空时，再进入聊天窗口。再加载20条信息时，目前是消息从最新的一条开始，逐条出来。
分析：
首先用户期望的是消息“一下子”一起出来。
目前的实现困难主要是，不知道一共有多少条历史消息，是否满20条。
逐条显示的好处是，当不足20条时，可以有多少条最终出多少条；超过20条时显示20条。
如果等20条都获取到再渲染，需要20条逐条获取。如果这时不足20条的话，就会一直停在那里等待。
建议：
还是先获取再一并渲染。为解决不知道是否有20条的问题，加一个时间限制。
1  当（获取条数 < 20  ||  获取时长 <= t) 时，持续获取；
2  将获取的消息队列进行渲染。（该队列可能是20条，可能不足20条）

**Comment by zkk333** [comment]
上述内容过了一遍  按照需求描述的显示了    再多试几次

**Comment by zkk333** [comment]
测试通过
