### ISSUE TITLE
Support customized for-me groups on different dapps - Backend

### ISSUE THREAD

**Issue by tanglepay-dev** [TanglePay/GroupFi-trollbox#216]

**Comment by zkk333** [comment]
测试通过，不同url对应不同的推荐群组
groupfi推荐群组：

![Image](https://github.com/TanglePay/GroupFi-trollbox/assets/42662926/ca86b724-69a4-497d-9d2f-a8d424fa248d)

tanglepay.com 推荐群组：


![Image](https://github.com/TanglePay/GroupFi-trollbox/assets/42662926/b7100ac3-dca4-41f0-9a06-100d09e5e952)

earlybee推荐群组：
smr-whale
