### ISSUE TITLE
首次进入网站，如果未检测到钱包，提示信息中应添加下载钱包的链接

### ISSUE THREAD

**Issue by MooreaV** [TanglePay/GroupFi-trollbox#217]
首次连接时，如果没有检测到钱包，trollbox会提示需要先安装钱包。这边Tanglepay这里应该是给一个可点的链接引导用户下载。

![Image](https://github.com/TanglePay/GroupFi-trollbox/assets/126679636/e35c9380-3fdf-4a7f-9fe4-152e5a00d84c)

**Comment by shiva01** [comment]
这个页面过一两个月会被干掉，所以先不做了。
未来连的钱包是跟着网站走的，也可能是mm钱包等。不连钱包时也可以有内容展示。
