### ISSUE TITLE
naming service: user initialization

### ISSUE THREAD

**Issue by shiva01** [TanglePay/GroupFi-trollbox#220]
Please read the product document: 
https://www.dropbox.com/scl/fi/tr29c87rcma4eh55rpsj1/User-account-initialization.paper?rlkey=9k9ympa9t1scmsp6ryn312ip9&dl=0
![Image](https://github.com/TanglePay/GroupFi-trollbox/assets/7235117/e60e13c5-4132-47c9-b181-c177abe99ae6)
![Image](https://github.com/TanglePay/GroupFi-trollbox/assets/7235117/fec94d26-cef2-44d1-8d44-1b796b0c96be)

**Comment by zkk333** [comment]
暂时修改名字的还没做
