### ISSUE TITLE
GroupFi的链的连接问题

### ISSUE THREAD

**Issue by shiva01** [TanglePay/GroupFi-trollbox#314]
当钱包连接的链groupfi不支持时，
提示：
GroupFi only supports xxxxx currently.

1）xxxxx，目前为shimmer mainnet。未来支持更多链后会添加；
2）样式与“creating public key”一致

**Comment by time-endless** [comment]
FYI, 改这个需求的时候，代码改起来不是那么舒服，需要优化下代码。

**Comment by zkk333** [comment]
测试通过
