### ISSUE TITLE
优化-目前存在打开groupfi.ai、iotabee.com、tanglepay.com时，有概率性获取不到最新js资源，导致最小化trollbox 时会出现一直转圈圈的页面，需要清缓存才能避免掉，需要优化成进入网站的时候100%可以拿到最新js资源的效果？

### ISSUE THREAD

**Issue by shiva01** [TanglePay/GroupFi-trollbox#323]
![Image](https://github.com/TanglePay/GroupFi-trollbox/assets/42662926/cac7aff7-c0bc-46c4-8276-240e759e2943)

**Comment by zkk333** [comment]
后续补充 ：复现了另一种情况 也出现缩小后 还有一个trollbox的问题 @time-endless  靠你了 

![Image](https://github.com/TanglePay/GroupFi-trollbox/assets/42662926/ce3503cd-947e-461e-b3e8-a034b3396844)

**Comment by zkk333** [comment]
应该是没问题了
