### ISSUE TITLE
页面加载时会出现多余的提示

### ISSUE THREAD

**Issue by shiva01** [TanglePay/GroupFi-trollbox#368]
如视频中，显示了：pls connect to ... wallet那个提示。
有时还会出现其他的多余提示，如：no available groups。

这些提示都应该在确定有这样的问题时才出现。

https://github.com/TanglePay/GroupFi-trollbox/assets/7235117/45a60377-df27-4688-9708-b1d75babe0ea

**Comment by time-endless** [comment]
1. 出现  “no available groups。” 是个 Bug，需要修复下。
2. 出现 “pls connect to ... wallet” 好像有点不好处理。Dapp 集成 Trollbox 的流程是：
       1. 加载 Trollbox iframe, 此时就会渲染 Trollbox
       2. Dapp 和 Trollbox i通信一次，确认通信状态 ok
       3. Dapp 告诉 Trollbox，Dapp 连接了 TanglePay

  Trollbox 在（1) 的时候就会渲染， 在接受到 （3） 之后才知道要连接哪个钱包，(1) 和 (3) 之间的这段时间里，由于不知道Dapp 选择了什么钱包，就会出现 “pls connect to ... wallet”

**Comment by time-endless** [comment]
Groupfi.ai 已经部署

**Comment by zkk333** [comment]
早已上线
