### ISSUE TITLE
EVM groupfi 添加一个announcement的群组

### ISSUE THREAD

**Issue by MooreaV** [TanglePay/GroupFi-trollbox#542]
名字可以叫groupfi annoucement，跟smr上的一样，但是需要修改这个群聊的设计：

这个群组只有某个网站的项目方/员工才可以说话，也就是说普通用户只能subscribe和unsubscribe，不需要提示 Buy XXX（ token/NFT) to speak in the group 。因此：

1）join/leave 改为subscribe/unsubscribe

2）没有提示用户买币/NFT的信息提示，

3）组的属性默认是public

**Comment by shiva01** [comment]
同需求376
https://github.com/orgs/TanglePay/projects/1/views/2?sliceBy%5Bvalue%5D=theuniverse&pane=issue&itemId=56535005
